dc_domain: dc.local
lab_subnet_cidr: 192.168.1.0/24

# DNS: не трогаем systemd-resolved, работаем через /etc/hosts
dns_mode: hosts_only          # dnsmasq | hosts_only
dns_server_ip: 192.168.1.229  # не используется в hosts_only, но оставим для полноты
manage_resolv_conf: false
manage_etc_hosts: true

# common
common_timezone: "Asia/Almaty"
common_locale: "ru_RU.UTF-8"
ssh_allow_users: [hlebushek]

# firewall
fw_enable: false
fw_mgmt_ssh_port: 22
fw_log_drops: false

# clickhouse base
ch_http_port: 8123
ch_tcp_port: 9000
cluster_name: cluster_3x3
